[package]
name = "test-macros"
version.workspace = true
edition.workspace = true
authors.workspace = true

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.52"
quote = "1.0.26"
syn = { version = "2.0.0", features = ["full"] }

glob = "0.3.1"
relative-path = "1.8.0"
